import { exportWorkInstructionAndResultsToCSV } from '../../src/logic/data-persistence';
import * as dataPersistence from '../../src/logic/data-persistence';

describe('SCEN-1160: exportWorkInstructionAndResultsToCSV - All search conditions null/undefined', () => {
  it('should generate CSV with all data when all search condition parameters are null/undefined', async () => {
    const mockWorkInstructions = [
      {
        workInstructionId: 'wi-1',
        facilityId: 'fac-1',
        teamId: 'team-1',
        workInstructionNumber: 'WI001',
        workName: 'Assembly',
        plannedStartDateTime: '2024-01-15T08:00:00Z',
        plannedEndDateTime: '2024-01-15T12:00:00Z',
        actualStartDateTime: '2024-01-15T08:05:00Z',
        actualEndDateTime: '2024-01-15T11:55:00Z',
        progressStatus: 'completed',
        progressRate: 100,
        requiredWorkerCount: 3,
        priority: 'high',
        createdAt: '2024-01-15T07:00:00Z',
        updatedAt: '2024-01-15T12:01:00Z',
        createdBy: 'user-admin',
        updatedBy: 'user-admin',
        workDescription: 'Assembly task description',
      },
      {
        workInstructionId: 'wi-2',
        facilityId: 'fac-1',
        teamId: 'team-2',
        workInstructionNumber: 'WI002',
        workName: 'Inspection',
        plannedStartDateTime: '2024-01-15T13:00:00Z',
        plannedEndDateTime: '2024-01-15T17:00:00Z',
        actualStartDateTime: undefined,
        actualEndDateTime: undefined,
        progressStatus: 'not_started',
        progressRate: 0,
        requiredWorkerCount: 2,
        priority: 'medium',
        createdAt: '2024-01-15T07:00:00Z',
        updatedAt: '2024-01-15T07:00:00Z',
        createdBy: 'user-admin',
        updatedBy: undefined,
        workDescription: 'Inspection task description',
      },
      {
        workInstructionId: 'wi-3',
        facilityId: 'fac-2',
        teamId: 'team-3',
        workInstructionNumber: 'WI003',
        workName: 'Packing',
        plannedStartDateTime: '2024-01-15T09:00:00Z',
        plannedEndDateTime: '2024-01-15T16:00:00Z',
        actualStartDateTime: '2024-01-15T09:10:00Z',
        actualEndDateTime: undefined,
        progressStatus: 'in_progress',
        progressRate: 50,
        requiredWorkerCount: 4,
        priority: 'high',
        createdAt: '2024-01-15T08:00:00Z',
        updatedAt: '2024-01-15T10:30:00Z',
        createdBy: 'user-admin',
        updatedBy: 'user-supervisor',
        workDescription: 'Packing task description',
      },
      {
        workInstructionId: 'wi-4',
        facilityId: 'fac-2',
        teamId: 'team-1',
        workInstructionNumber: 'WI004',
        workName: 'Quality Check',
        plannedStartDateTime: '2024-01-16T08:00:00Z',
        plannedEndDateTime: '2024-01-16T12:00:00Z',
        actualStartDateTime: undefined,
        actualEndDateTime: undefined,
        progressStatus: 'not_started',
        progressRate: 0,
        requiredWorkerCount: 2,
        priority: 'low',
        createdAt: '2024-01-15T14:00:00Z',
        updatedAt: '2024-01-15T14:00:00Z',
        createdBy: 'user-admin',
        updatedBy: undefined,
        workDescription: 'Quality check task description',
      },
      {
        workInstructionId: 'wi-5',
        facilityId: 'fac-1',
        teamId: 'team-1',
        workInstructionNumber: 'WI005',
        workName: 'Labeling',
        plannedStartDateTime: '2024-01-15T14:00:00Z',
        plannedEndDateTime: '2024-01-15T18:00:00Z',
        actualStartDateTime: '2024-01-15T14:15:00Z',
        actualEndDateTime: '2024-01-15T17:45:00Z',
        progressStatus: 'completed',
        progressRate: 100,
        requiredWorkerCount: 1,
        priority: 'low',
        createdAt: '2024-01-15T13:00:00Z',
        updatedAt: '2024-01-15T17:46:00Z',
        createdBy: 'user-admin',
        updatedBy: 'user-admin',
        workDescription: 'Labeling task description',
      },
    ];

    const mockWorkResults = [
      {
        workResultId: 'wr-1',
        workInstructionId: 'wi-1',
        workerId: 'worker-1',
        facilityId: 'fac-1',
        teamId: 'team-1',
        actualStartDateTime: '2024-01-15T08:05:00Z',
        actualEndDateTime: '2024-01-15T11:55:00Z',
        actualQuantity: 150,
        workStatus: 'completed',
        defectCount: 2,
        remarks: 'Completed with minor defects',
        createdAt: '2024-01-15T11:56:00Z',
        updatedAt: '2024-01-15T11:56:00Z',
        createdBy: 'worker-1',
        updatedBy: undefined,
      },
      {
        workResultId: 'wr-2',
        workInstructionId: 'wi-1',
        workerId: 'worker-2',
        facilityId: 'fac-1',
        teamId: 'team-1',
        actualStartDateTime: '2024-01-15T08:05:00Z',
        actualEndDateTime: '2024-01-15T11:55:00Z',
        actualQuantity: 145,
        workStatus: 'completed',
        defectCount: 0,
        remarks: 'Completed successfully',
        createdAt: '2024-01-15T11:56:00Z',
        updatedAt: '2024-01-15T11:56:00Z',
        createdBy: 'worker-2',
        updatedBy: undefined,
      },
      {
        workResultId: 'wr-3',
        workInstructionId: 'wi-3',
        workerId: 'worker-3',
        facilityId: 'fac-2',
        teamId: 'team-3',
        actualStartDateTime: '2024-01-15T09:10:00Z',
        actualEndDateTime: undefined,
        actualQuantity: 75,
        workStatus: 'in_progress',
        defectCount: undefined,
        remarks: 'In progress',
        createdAt: '2024-01-15T09:11:00Z',
        updatedAt: '2024-01-15T10:30:00Z',
        createdBy: 'worker-3',
        updatedBy: 'worker-3',
      },
      {
        workResultId: 'wr-4',
        workInstructionId: 'wi-5',
        workerId: 'worker-1',
        facilityId: 'fac-1',
        teamId: 'team-1',
        actualStartDateTime: '2024-01-15T14:15:00Z',
        actualEndDateTime: '2024-01-15T17:45:00Z',
        actualQuantity: 200,
        workStatus: 'completed',
        defectCount: 0,
        remarks: 'Completed successfully',
        createdAt: '2024-01-15T17:46:00Z',
        updatedAt: '2024-01-15T17:46:00Z',
        createdBy: 'worker-1',
        updatedBy: undefined,
      },
      {
        workResultId: 'wr-5',
        workInstructionId: 'wi-2',
        workerId: 'worker-4',
        facilityId: 'fac-1',
        teamId: 'team-2',
        actualStartDateTime: undefined,
        actualEndDateTime: undefined,
        actualQuantity: 0,
        workStatus: 'not_started',
        defectCount: undefined,
        remarks: undefined,
        createdAt: '2024-01-15T13:00:00Z',
        updatedAt: '2024-01-15T13:00:00Z',
        createdBy: 'user-admin',
        updatedBy: undefined,
      },
      {
        workResultId: 'wr-6',
        workInstructionId: 'wi-3',
        workerId: 'worker-4',
        facilityId: 'fac-2',
        teamId: 'team-3',
        actualStartDateTime: '2024-01-15T09:15:00Z',
        actualEndDateTime: undefined,
        actualQuantity: 60,
        workStatus: 'in_progress',
        defectCount: undefined,
        remarks: 'Ongoing',
        createdAt: '2024-01-15T09:16:00Z',
        updatedAt: '2024-01-15T10:00:00Z',
        createdBy: 'worker-4',
        updatedBy: 'worker-4',
      },
      {
        workResultId: 'wr-7',
        workInstructionId: 'wi-1',
        workerId: 'worker-3',
        facilityId: 'fac-1',
        teamId: 'team-1',
        actualStartDateTime: '2024-01-15T08:05:00Z',
        actualEndDateTime: '2024-01-15T11:55:00Z',
        actualQuantity: 155,
        workStatus: 'completed',
        defectCount: 1,
        remarks: 'Completed with 1 defect',
        createdAt: '2024-01-15T11:56:00Z',
        updatedAt: '2024-01-15T11:56:00Z',
        createdBy: 'worker-3',
        updatedBy: undefined,
      },
      {
        workResultId: 'wr-8',
        workInstructionId: 'wi-5',
        workerId: 'worker-2',
        facilityId: 'fac-1',
        teamId: 'team-1',
        actualStartDateTime: '2024-01-15T14:15:00Z',
        actualEndDateTime: '2024-01-15T17:45:00Z',
        actualQuantity: 195,
        workStatus: 'completed',
        defectCount: 0,
        remarks: 'Completed successfully',
        createdAt: '2024-01-15T17:46:00Z',
        updatedAt: '2024-01-15T17:46:00Z',
        createdBy: 'worker-2',
        updatedBy: undefined,
      },
      {
        workResultId: 'wr-9',
        workInstructionId: 'wi-2',
        workerId: 'worker-1',
        facilityId: 'fac-1',
        teamId: 'team-2',
        actualStartDateTime: undefined,
        actualEndDateTime: undefined,
        actualQuantity: 0,
        workStatus: 'not_started',
        defectCount: undefined,
        remarks: undefined,
        createdAt: '2024-01-15T13:00:00Z',
        updatedAt: '2024-01-15T13:00:00Z',
        createdBy: 'user-admin',
        updatedBy: undefined,
      },
      {
        workResultId: 'wr-10',
        workInstructionId: 'wi-4',
        workerId: 'worker-5',
        facilityId: 'fac-2',
        teamId: 'team-1',
        actualStartDateTime: undefined,
        actualEndDateTime: undefined,
        actualQuantity: 0,
        workStatus: 'not_started',
        defectCount: undefined,
        remarks: undefined,
        createdAt: '2024-01-15T14:00:00Z',
        updatedAt: '2024-01-15T14:00:00Z',
        createdBy: 'user-admin',
        updatedBy: undefined,
      },
    ];

    const mockProductivityData = [
      {
        productivityDataId: 'pd-1',
        workResultId: 'wr-1',
        workerId: 'worker-1',
        facilityId: 'fac-1',
        teamId: 'team-1',
        workDate: '2024-01-15',
        plannedWorkTime: 240,
        actualWorkTime: 230,
        completedItemCount: 150,
        productivityRate: 95,
        qualityScore: 98,
        errorCount: 2,
        proficiencyLevel: 'advanced',
        remarks: 'High productivity',
        createdAt: '2024-01-15T12:00:00Z',
        updatedAt: '2024-01-15T12:00:00Z',
        createdBy: 'worker-1',
        updatedBy: undefined,
      },
      {
        productivityDataId: 'pd-2',
        workResultId: 'wr-2',
        workerId: 'worker-2',
        facilityId: 'fac-1',
        teamId: 'team-1',
        workDate: '2024-01-15',
        plannedWorkTime: 240,
        actualWorkTime: 235,
        completedItemCount: 145,
        productivityRate: 92,
        qualityScore: 100,
        errorCount: 0,
        proficiencyLevel: 'advanced',
        remarks: 'Excellent quality',
        createdAt: '2024-01-15T12:00:00Z',
        updatedAt: '2024-01-15T12:00:00Z',
        createdBy: 'worker-2',
        updatedBy: undefined,
      },
      {
        productivityDataId: 'pd-3',
        workResultId: 'wr-3',
        workerId: 'worker-3',
        facilityId: 'fac-2',
        teamId: 'team-3',
        workDate: '2024-01-15',
        plannedWorkTime: 480,
        actualWorkTime: 300,
        completedItemCount: 75,
        productivityRate: 75,
        qualityScore: 85,
        errorCount: 5,
        proficiencyLevel: 'intermediate',
        remarks: 'In progress',
        createdAt: '2024-01-15T10:30:00Z',
        updatedAt: '2024-01-15T10:30:00Z',
        createdBy: 'worker-3',
        updatedBy: undefined,
      },
      {
        productivityDataId: 'pd-4',
        workResultId: 'wr-4',
        workerId: 'worker-1',
        facilityId: 'fac-1',
        teamId: 'team-1',
        workDate: '2024-01-15',
        plannedWorkTime: 240,
        actualWorkTime: 210,
        completedItemCount: 200,
        productivityRate: 105,
        qualityScore: 100,
        errorCount: 0,
        proficiencyLevel: 'advanced',
        remarks: 'Exceeds target',
        createdAt: '2024-01-15T17:46:00Z',
        updatedAt: '2024-01-15T17:46:00Z',
        createdBy: 'worker-1',
        updatedBy: undefined,
      },
      {
        productivityDataId: 'pd-5',
        workResultId: 'wr-7',
        workerId: 'worker-3',
        facilityId: 'fac-1',
        teamId: 'team-1',
        workDate: '2024-01-15',
        plannedWorkTime: 240,
        actualWorkTime: 235,
        completedItemCount: 155,
        productivityRate: 96,
        qualityScore: 95,
        errorCount: 1,
        proficiencyLevel: 'advanced',
        remarks: 'Good performance',
        createdAt: '2024-01-15T12:00:00Z',
        updatedAt: '2024-01-15T12:00:00Z',
        createdBy: 'worker-3',
        updatedBy: undefined,
      },
      {
        productivityDataId: 'pd-6',
        workResultId: 'wr-8',
        workerId: 'worker-2',
        facilityId: 'fac-1',
        teamId: 'team-1',
        workDate: '2024-01-15',
        plannedWorkTime: 240,
        actualWorkTime: 215,
        completedItemCount: 195,
        productivityRate: 100,
        qualityScore: 100,
        errorCount: 0,
        proficiencyLevel: 'advanced',
        remarks: 'Excellent',
        createdAt: '2024-01-15T17:46:00Z',
        updatedAt: '2024-01-15T17:46:00Z',
        createdBy: 'worker-2',
        updatedBy: undefined,
      },
      {
        productivityDataId: 'pd-7',
        workResultId: 'wr-6',
        workerId: 'worker-4',
        facilityId: 'fac-2',
        teamId: 'team-3',
        workDate: '2024-01-15',
        plannedWorkTime: 480,
        actualWorkTime: 250,
        completedItemCount: 60,
        productivityRate: 70,
        qualityScore: 80,
        errorCount: 8,
        proficiencyLevel: 'beginner',
        remarks: 'Learning phase',
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-01-15T10:00:00Z',
        createdBy: 'worker-4',
        updatedBy: undefined,
      },
      {
        productivityDataId: 'pd-8',
        workResultId: 'wr-5',
        workerId: 'worker-4',
        facilityId: 'fac-1',
        teamId: 'team-2',
        workDate: '2024-01-15',
        plannedWorkTime: 480,
        actualWorkTime: 0,
        completedItemCount: 0,
        productivityRate: 0,
        qualityScore: 0,
        errorCount: 0,
        proficiencyLevel: 'beginner',
        remarks: 'Not started',
        createdAt: '2024-01-15T13:00:00Z',
        updatedAt: '2024-01-15T13:00:00Z',
        createdBy: 'user-admin',
        updatedBy: undefined,
      },
      {
        productivityDataId: 'pd-9',
        workResultId: 'wr-9',
        workerId: 'worker-1',
        facilityId: 'fac-1',
        teamId: 'team-2',
        workDate: '2024-01-15',
        plannedWorkTime: 480,
        actualWorkTime: 0,
        completedItemCount: 0,
        productivityRate: 0,
        qualityScore: 0,
        errorCount: 0,
        proficiencyLevel: 'advanced',
        remarks: 'Not started',
        createdAt: '2024-01-15T13:00:00Z',
        updatedAt: '2024-01-15T13:00:00Z',
        createdBy: 'user-admin',
        updatedBy: undefined,
      },
      {
        productivityDataId: 'pd-10',
        workResultId: 'wr-10',
        workerId: 'worker-5',
        facilityId: 'fac-2',
        teamId: 'team-1',
        workDate: '2024-01-16',
        plannedWorkTime: 480,
        actualWorkTime: 0,
        completedItemCount: 0,
        productivityRate: 0,
        qualityScore: 0,
        errorCount: 0,
        proficiencyLevel: 'intermediate',
        remarks: 'Scheduled for tomorrow',
        createdAt: '2024-01-15T14:00:00Z',
        updatedAt: '2024-01-15T14:00:00Z',
        createdBy: 'user-admin',
        updatedBy: undefined,
      },
      {
        productivityDataId: 'pd-11',
        workResultId: 'wr-1',
        workerId: 'worker-1',
        facilityId: 'fac-1',
        teamId: 'team-1',
        workDate: '2024-01-16',
        plannedWorkTime: 240,
        actualWorkTime: 240,
        completedItemCount: 160,
        productivityRate: 98,
        qualityScore: 97,
        errorCount: 1,
        proficiencyLevel: 'advanced',
        remarks: 'Consistent',
        createdAt: '2024-01-16T12:00:00Z',
        updatedAt: '2024-01-16T12:00:00Z',
        createdBy: 'worker-1',
        updatedBy: undefined,
      },
      {
        productivityDataId: 'pd-12',
        workResultId: 'wr-2',
        workerId: 'worker-2',
        facilityId: 'fac-1',
        teamId: 'team-1',
        workDate: '2024-01-16',
        plannedWorkTime: 240,
        actualWorkTime: 240,
        completedItemCount: 150,
        productivityRate: 95,
        qualityScore: 100,
        errorCount: 0,
        proficiencyLevel: 'advanced',
        remarks: 'Excellent',
        createdAt: '2024-01-16T12:00:00Z',
        updatedAt: '2024-01-16T12:00:00Z',
        createdBy: 'worker-2',
        updatedBy: undefined,
      },
      {
        productivityDataId: 'pd-13',
        workResultId: 'wr-3',
        workerId: 'worker-3',
        facilityId: 'fac-2',
        teamId: 'team-3',
        workDate: '2024-01-16',
        plannedWorkTime: 480,
        actualWorkTime: 350,
        completedItemCount: 85,
        productivityRate: 80,
        qualityScore: 88,
        errorCount: 4,
        proficiencyLevel: 'intermediate',
        remarks: 'Improving',
        createdAt: '2024-01-16T10:30:00Z',
        updatedAt: '2024-01-16T10:30:00Z',
        createdBy: 'worker-3',
        updatedBy: undefined,
      },
      {
        productivityDataId: 'pd-14',
        workResultId: 'wr-6',
        workerId: 'worker-4',
        facilityId: 'fac-2',
        teamId: 'team-3',
        workDate: '2024-01-16',
        plannedWorkTime: 480,
        actualWorkTime: 300,
        completedItemCount: 70,
        productivityRate: 75,
        qualityScore: 82,
        errorCount: 6,
        proficiencyLevel: 'beginner',
        remarks: 'Learning phase',
        createdAt: '2024-01-16T10:00:00Z',
        updatedAt: '2024-01-16T10:00:00Z',
        createdBy: 'worker-4',
        updatedBy: undefined,
      },
      {
        productivityDataId: 'pd-15',
        workResultId: 'wr-4',
        workerId: 'worker-1',
        facilityId: 'fac-1',
        teamId: 'team-1',
        workDate: '2024-01-16',
        plannedWorkTime: 240,
        actualWorkTime: 220,
        completedItemCount: 210,
        productivityRate: 107,
        qualityScore: 99,
        errorCount: 0,
        proficiencyLevel: 'advanced',
        remarks: 'Exceeds target consistently',
        createdAt: '2024-01-16T17:46:00Z',
        updatedAt: '2024-01-16T17:46:00Z',
        createdBy: 'worker-1',
        updatedBy: undefined,
      },
    ];

    const mockHandyTerminalSyncLogs = [
      {
        handyTerminalSyncLogId: 'ht-log-1',
        workerId: 'worker-1',
        handyTerminalId: 'terminal-1',
        facilityId: 'fac-1',
        syncType: 'work_result_sync',
        workInstructionId: 'wi-1',
        syncContent: JSON.stringify({ quantity: 150, timestamp: '2024-01-15T11:55:00Z' }),
        syncStatus: 'success',
        errorMessage: null,
        sentDateTime: '2024-01-15T11:55:00Z',
        receivedDateTime: '2024-01-15T11:55:05Z',
        processingCompletedDateTime: '2024-01-15T11:55:10Z',
        retryCount: 0,
        createdAt: '2024-01-15T11:55:10Z',
        updatedAt: '2024-01-15T11:55:10Z',
        createdBy: 'system',
        updatedBy: undefined,
      },
      {
        handyTerminalSyncLogId: 'ht-log-2',
        workerId: 'worker-2',
        handyTerminalId: 'terminal-2',
        facilityId: 'fac-1',
        syncType: 'work_result_sync',
        workInstructionId: 'wi-1',
        syncContent: JSON.stringify({ quantity: 145, timestamp: '2024-01-15T11:55:00Z' }),
        syncStatus: 'success',
        errorMessage: null,
        sentDateTime: '2024-01-15T11:55:00Z',
        receivedDateTime: '2024-01-15T11:55:06Z',
        processingCompletedDateTime: '2024-01-15T11:55:11Z',
        retryCount: 0,
        createdAt: '2024-01-15T11:55:11Z',
        updatedAt: '2024-01-15T11:55:11Z',
        createdBy: 'system',
        updatedBy: undefined,
      },
      {
        handyTerminalSyncLogId: 'ht-log-3',
        workerId: 'worker-3',
        handyTerminalId: 'terminal-3',
        facilityId: 'fac-2',
        syncType: 'work_result_sync',
        workInstructionId: 'wi-3',
        syncContent: JSON.stringify({ quantity: 75, timestamp: '2024-01-15T10:30:00Z' }),
        syncStatus: 'success',
        errorMessage: null,
        sentDateTime: '2024-01-15T10:30:00Z',
        receivedDateTime: '2024-01-15T10:30:05Z',
        processingCompletedDateTime: '2024-01-15T10:30:10Z',
        retryCount: 0,
        createdAt: '2024-01-15T10:30:10Z',
        updatedAt: '2024-01-15T10:30:10Z',
        createdBy: 'system',
        updatedBy: undefined,
      },
      {
        handyTerminalSyncLogId: 'ht-log-4',
        workerId: 'worker-1',
        handyTerminalId: 'terminal-1',
        facilityId: 'fac-1',
        syncType: 'status_update',
        workInstructionId: 'wi-5',
        syncContent: JSON.stringify({ status: 'completed', timestamp: '2024-01-15T17:45:00Z' }),
        syncStatus: 'success',
        errorMessage: null,
        sentDateTime: '2024-01-15T17:45:00Z',
        receivedDateTime: '2024-01-15T17:45:05Z',
        processingCompletedDateTime: '2024-01-15T17:45:10Z',
        retryCount: 0,
        createdAt: '2024-01-15T17:45:10Z',
        updatedAt: '2024-01-15T17:45:10Z',
        createdBy: 'system',
        updatedBy: undefined,
      },
      {
        handyTerminalSyncLogId: 'ht-log-5',
        workerId: 'worker-4',
        handyTerminalId: 'terminal-4',
        facilityId: 'fac-1',
        syncType: 'status_update',
        workInstructionId: 'wi-2',
        syncContent: JSON.stringify({ status: 'not_started', timestamp: '2024-01-15T13:00:00Z' }),
        syncStatus: 'success',
        errorMessage: null,
        sentDateTime: '2024-01-15T13:00:00Z',
        receivedDateTime: '2024-01-15T13:00:05Z',
        processingCompletedDateTime: '2024-01-15T13:00:10Z',
        retryCount: 0,
        createdAt: '2024-01-15T13:00:10Z',
        updatedAt: '2024-01-15T13:00:10Z',
        createdBy: 'system',
        updatedBy: undefined,
      },
      {
        handyTerminalSyncLogId: 'ht-log-6',
        workerId: 'worker-3',
        handyTerminalId: 'terminal-3',
        facilityId: 'fac-2',
        syncType: 'work_result_sync',
        workInstructionId: 'wi-3',
        syncContent: JSON.stringify({ quantity: 60, timestamp: '2024-01-15T10:00:00Z' }),
        syncStatus: 'success',
        errorMessage: null,
        sentDateTime: '2024-01-15T10:00:00Z',
        receivedDateTime: '2024-01-15T10:00:05Z',
        processingCompletedDateTime: '2024-01-15T10:00:10Z',
        retryCount: 0,
        createdAt: '2024-01-15T10:00:10Z',
        updatedAt: '2024-01-15T10:00:10Z',
        createdBy: 'system',
        updatedBy: undefined,
      },
      {
        handyTerminalSyncLogId: 'ht-log-7',
        workerId: 'worker-2',
        handyTerminalId: 'terminal-2',
        facilityId: 'fac-1',
        syncType: 'work_result_sync',
        workInstructionId: 'wi-5',
        syncContent: JSON.stringify({ quantity: 195, timestamp: '2024-01-15T17:45:00Z' }),
        syncStatus: 'success',
        errorMessage: null,
        sentDateTime: '2024-01-15T17:45:00Z',
        receivedDateTime: '2024-01-15T17:45:05Z',
        processingCompletedDateTime: '2024-01-15T17:45:10Z',
        retryCount: 0,
        createdAt: '2024-01-15T17:45:10Z',
        updatedAt: '2024-01-15T17:45:10Z',
        createdBy: 'system',
        updatedBy: undefined,
      },
      {
        handyTerminalSyncLogId: 'ht-log-8',
        workerId: 'worker-1',
        handyTerminalId: 'terminal-1',
        facilityId: 'fac-1',
        syncType: 'position_update',
        workInstructionId: null,
        syncContent: JSON.stringify({ position: 'assembly_station_1', timestamp: '2024-01-15T08:00:00Z' }),
        syncStatus: 'success',
        errorMessage: null,
        sentDateTime: '2024-01-15T08:00:00Z',
        receivedDateTime: '2024-01-15T08:00:05Z',
        processingCompletedDateTime: '2024-01-15T08:00:10Z',
        retryCount: 0,
        createdAt: '2024-01-15T08:00:10Z',
        updatedAt: '2024-01-15T08:00:10Z',
        createdBy: 'system',
        updatedBy: undefined,
      },
    ];

    const mockFacilities: { [key: string]: any } = {
      'fac-1': {
        facilityId: 'fac-1',
        facilityName: 'Facility 1',
        facilityCode: 'FAC001',
        address: '123 Main St',
        maxCapacity: 100,
        currentCapacity: 50,
        operatingStatus: 'active',
        responsiblePersonName: 'John Doe',
        contactInfo: '555-1234',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-15T00:00:00Z',
        createdBy: 'admin',
        updatedBy: 'admin',
      },
      'fac-2': {
        facilityId: 'fac-2',
        facilityName: 'Facility 2',
        facilityCode: 'FAC002',
        address: '456 Oak Ave',
        maxCapacity: 80,
        currentCapacity: 40,
        operatingStatus: 'active',
        responsiblePersonName: 'Jane Smith',
        contactInfo: '555-5678',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-15T00:00:00Z',
        createdBy: 'admin',
        updatedBy: 'admin',
      },
    };

    const mockTeams: { [key: string]: any } = {
      'team-1': {
        teamId: 'team-1',
        teamName: 'Team A',
        facilityId: 'fac-1',
        teamLeaderId: 'worker-1',
        operatingStatus: 'active',
        capacity: 10,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-15T00:00:00Z',
        createdBy: 'admin',
      },
      'team-2': {
        teamId: 'team-2',
        teamName: 'Team B',
        facilityId: 'fac-1',
        teamLeaderId: 'worker-2',
        operatingStatus: 'active',
        capacity: 8,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-15T00:00:00Z',
        createdBy: 'admin',
      },
      'team-3': {
        teamId: 'team-3',
        teamName: 'Team C',
        facilityId: 'fac-2',
        teamLeaderId: 'worker-3',
        operatingStatus: 'active',
        capacity: 12,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-15T00:00:00Z',
        createdBy: 'admin',
      },
    };

    const mockWorkers: { [key: string]: any } = {
      'worker-1': {
        workerId: 'worker-1',
        workerName: 'Alice Johnson',
        facilityId: 'fac-1',
        teamId: 'team-1',
        jobType: 'assembly',
        operatingStatus: 'active',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-15T00:00:00Z',
        createdBy: 'admin',
      },
      'worker-2': {
        workerId: 'worker-2',
        workerName: 'Bob Smith',
        facilityId: 'fac-1',
        teamId: 'team-1',
        jobType: 'assembly',
        operatingStatus: 'active',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-15T00:00:00Z',
        createdBy: 'admin',
      },
      'worker-3': {
        workerId: 'worker-3',
        workerName: 'Carol White',
        facilityId: 'fac-2',
        teamId: 'team-3',
        jobType: 'packing',
        operatingStatus: 'active',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-15T00:00:00Z',
        createdBy: 'admin',
      },
      'worker-4': {
        workerId: 'worker-4',
        workerName: 'David Brown',
        facilityId: 'fac-2',
        teamId: 'team-3',
        jobType: 'packing',
        operatingStatus: 'active',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-15T00:00:00Z',
        createdBy: 'admin',
      },
      'worker-5': {
        workerId: 'worker-5',
        workerName: 'Eve Davis',
        facilityId: 'fac-2',
        teamId: 'team-1',
        jobType: 'inspection',
        operatingStatus: 'active',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-15T00:00:00Z',
        createdBy: 'admin',
      },
    };

    jest.spyOn(dataPersistence, 'listWorkInstructionsByCondition').mockResolvedValue({
      workInstructions: mockWorkInstructions,
      totalCount: mockWorkInstructions.length,
      pageNumber: null,
      pageSize: null,
      retrievedAt: new Date().toISOString(),
    });

    jest.spyOn(dataPersistence, 'listWorkResultsByCondition').mockResolvedValue({
      workResults: mockWorkResults,
      totalCount: mockWorkResults.length,
      pageNumber: null,
      pageSize: null,
      retrievedAt: new Date().toISOString(),
    });

    jest.spyOn(dataPersistence, 'listProductivityDataByCondition').mockResolvedValue({
      productivityDataList: mockProductivityData,
      totalCount: mockProductivityData.length,
      pageNumber: null,
      pageSize: null,
      retrievedAt: new Date().toISOString(),
    });

    jest.spyOn(dataPersistence, 'listHandyTerminalSyncLogByCondition').mockResolvedValue({
      handyTerminalSyncLogs: mockHandyTerminalSyncLogs,
      totalCount: mockHandyTerminalSyncLogs.length,
      pageNumber: null,
      pageSize: null,
      retrievedAt: new Date().toISOString(),
    });

    jest.spyOn(dataPersistence, 'getWorkerById').mockImplementation(async (input) => {
      return mockWorkers[input.workerId] || { workerId: input.workerId, workerName: 'Unknown' };
    });

    jest.spyOn(dataPersistence, 'getFacilityById').mockImplementation(async (input) => {
      return mockFacilities[input.facilityId] || { facilityId: input.facilityId, facilityName: 'Unknown' };
    });

    jest.spyOn(dataPersistence, 'getTeamById').mockImplementation(async (input) => {
      return mockTeams[input.teamId] || { teamId: input.teamId, teamName: 'Unknown' };
    });

    const inputWithNull = {
      workInstructionIds: null,
      facilityIds: null,
      teamIds: null,
      workerIds: null,
      workInstructionNumbers: null,
      progressStatuses: null,
      plannedStartFromDateTime: null,
      plannedStartToDateTime: null,
      plannedEndFromDateTime: null,
      plannedEndToDateTime: null,
      actualStartFromDateTime: null,
      actualStartToDateTime: null,
      actualEndFromDateTime: null,
      actualEndToDateTime: null,
      minProgressRate: null,
      maxProgressRate: null,
      minProductivityRate: null,
      maxProductivityRate: null,
      handyTerminalSyncStatuses: null,
      sortBy: null,
      sortOrder: null,
      exportedBy: 'user-12345',
    };

    const resultWithNull = await exportWorkInstructionAndResultsToCSV(inputWithNull);

    expect(resultWithNull).toBeDefined();
    expect(resultWithNull.csvBinaryStream).toBeDefined();
    expect(resultWithNull.fileName).toBeDefined();
    expect(resultWithNull.mimeType).toBeDefined();
    expect(resultWithNull.recordCount).toBeDefined();
    expect(resultWithNull.exportedAt).toBeDefined();
    expect(resultWithNull.exportedBy).toBeDefined();

    expect(resultWithNull.csvBinaryStream).toBeInstanceOf(Buffer);
    expect(resultWithNull.csvBinaryStream.length).toBeGreaterThan(0);

    const csvContent = resultWithNull.csvBinaryStream.toString('utf-8');
    expect(csvContent).toContain('workInstructionId');

    const csvLines = csvContent.split('\n').filter(line => line.trim());
    expect(csvLines.length).toBeGreaterThan(1);

    const headerLine = csvLines[0];
    const headerColumns = headerLine.split(',').map(col => col.trim());
    expect(headerColumns.length).toBeGreaterThan(0);

    for (let i = 1; i < csvLines.length; i++) {
      const dataLine = csvLines[i];
      if (dataLine.trim()) {
        const colCount = (dataLine.match(/(?:^|,)(?:"[^"]*"|[^,]*)/g) || []).length;
        expect(colCount).toBe(headerColumns.length);
      }
    }

    expect(resultWithNull.fileName).toMatch(/^WorkInstructionAndResults_\d{8}_\d{6}\.csv$/);

    expect(resultWithNull.mimeType).toBe('text/csv');

    expect(resultWithNull.recordCount).toBeGreaterThan(0);

    expect(resultWithNull.exportedAt).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/);

    expect(resultWithNull.exportedBy).toBe('user-12345');

    expect(csvContent).toContain('WI001');
    expect(csvContent).toContain('Assembly');
    expect(csvContent).toContain('WI002');
    expect(csvContent).toContain('Inspection');
    expect(csvContent).toContain('WI003');
    expect(csvContent).toContain('Packing');

    expect(csvContent).toContain('worker-1');
    expect(csvContent).toContain('worker-2');
    expect(csvContent).toContain('completed');
    expect(csvContent).toContain('in_progress');

    expect(dataPersistence.listWorkInstructionsByCondition).toHaveBeenCalled();
    expect(dataPersistence.listWorkResultsByCondition).toHaveBeenCalled();
    expect(dataPersistence.listProductivityDataByCondition).toHaveBeenCalled();
    expect(dataPersistence.listHandyTerminalSyncLogByCondition).toHaveBeenCalled();
  });
});